In [1]:
import numpy as np

In [2]:
def f1(x , y):
    return np.sin(x + 2) - y - 1.5

In [3]:
def f2(x, y):
    return x + np.cos(y - 2) - 0.5

In [4]:
def A_inv(x, y):
    A = np.zeros((2, 2))
    A[0][0] = -np.sin(y - 2)
    A[0][1] = 1
    A[1][0] = -1
    A[1][1] = np.cos(x + 2)
    A = (1 / (1 - np.cos(x + 2)*np.sin(y-2))) * A
    return A

In [5]:
def NewtonForSystems(x0, y0):
    k = 1
    x_old = [0, 0]
    x_cur = [x0, y0]
    x_new = x_cur - np.dot(A_inv(x_cur[0], x_cur[1]), [f1(x_cur[0], x_cur[1]), f2(x_cur[0], x_cur[1])])
    while (abs(x_new[0] - x_cur[0]) >= (10**(-3))*(1 - (abs(x_new[0] - x_cur[0]) / abs(x_cur[0] - x_old[0]))) or abs(x_new[1] - x_cur[1]) >= (10**(-3))*(1 - (abs(x_new[1] - x_cur[1]) / abs(x_cur[1] - x_old[1])))):
        x_old = x_cur
        x_cur = x_new
        x_new = x_new - np.dot(A_inv(x_new[0], x_new[1]), [f1(x_new[0], x_new[1]), f2(x_new[0], x_new[1])])
        k += 1
    return x_new, k

В $x_{old}$ у меня хранится $x_{n-2}$, в $x_{cur}$ лежит $x_{n-1}$, а в $x_{new}$ - $x_{n}$ соответственно. Из-за того, что я кривой, сначала всегда делается одна итерация, а потом мы заходим в цикл, где по известным формулам обновляем значения всех иксов. $\newline$
В данной реализации я проверяю неравентво на норму ошибки для каждой компоненты вектора ответов. Это не совсем правильно, но, кажется, я таким образом покрываю манхэттенскую норму, поэтому как бы ошибки нет, но я переписал ниже правильно для евклидовой нормы.$\newline$
Сам критерий был взят из задачника Аристова-Завьялова-Лобанов издание 14го года страница 95 формулы 8.4 и 8.5.

In [16]:
def NewtonForSystems2(x0, y0):
    k = 1
    x_old = [0, 0]
    x_cur = [x0, y0]
    x_new = x_cur - np.dot(A_inv(x_cur[0], x_cur[1]), [f1(x_cur[0], x_cur[1]), f2(x_cur[0], x_cur[1])])
    while (np.sqrt((x_new[0] - x_cur[0])**2 + (x_new[1] - x_cur[1])**2) >= (10**(-3)) * 
           (1 - (np.sqrt((x_new[0] - x_cur[0])**2+(x_new[1] - x_cur[1])**2) / (np.sqrt((x_cur[0] - x_old[0])**2+(x_cur[1] - x_old[1])**2))))):
        x_old = x_cur
        x_cur = x_new
        x_new = x_new - np.dot(A_inv(x_new[0], x_new[1]), [f1(x_new[0], x_new[1]), f2(x_new[0], x_new[1])])
        k += 1
    return x_new, k

In [8]:
NewtonForSystems(1, -1)

(array([ 1.34633765, -1.70331749]), 4)

In [9]:
NewtonForSystems(-1, 2)

(array([ 1.34633764, -1.70331748]), 43)

In [10]:
NewtonForSystems(5, 10)

(array([ 1.34633767, -1.70331751]), 29)

In [17]:
NewtonForSystems2(1, -1)

(array([ 1.34633765, -1.70331749]), 4)

In [18]:
NewtonForSystems2(-1, 2)

(array([ 1.34633764, -1.70331748]), 43)

In [19]:
NewtonForSystems2(5, 10)

(array([ 1.34633767, -1.70331751]), 29)